### ISSUE TITLE
Jenkins Pipeline Syntax tool not picking up the plugin

### ISSUE THREAD

**Issue by udderchaos** [jenkinsci/azure-function-plugin#9]
Jenkins Pipeline Syntax tool doesn't seem to pick this plugin up on mine? - Perhaps I'm missing something

**Comment by gavinfish** [comment]
@udderchaos Do you mean that you cannot find this plugin in pipeline syntax generator? Its name should be like `azureFunctionAppPublish: Publish an Azure Function App`.

**Comment by udderchaos** [comment]
Yeah - It's not in my list. 
I'm using Jenkins ver. 2.150, the plugin's version is 0.2.1

**Comment by gavinfish** [comment]
It works fine for me. Could you please open your browser debugger(like debugger tools in Chrome) to check whether there is any errors in the console?
